### ISSUE TITLE
开启吸底模式后发现播放器窗口不对

### ISSUE THREAD

**Issue by csyphil** [kaygb/KZHomePage#3]
点开播放器拓宽（就那个>），会发现播放器下层还有一个白块窗口，且大小与播放器不均等。

**Comment by csyphil** [comment]
好吧，我切换回了旧版发现也一样，清除缓存后测试了下Chrome和Edge好像也一样。
emmmmmmmmmmmmm，不太清楚到底是哪里设置的问题。

**Comment by kaygb** [comment]
有图片吗

**Comment by kaygb** [comment]
上传到 https://sm.ms/  然后在这里回复图片链接

**Comment by kaygb** [comment]
已修复
